### ISSUE TITLE
Fast Travel Not Working + Labels Stay After Removing

### ISSUE THREAD

**Issue by DarkWhiteParadox** [Rikshy/AntiqueAtlasExtras#11]
Players can't fast travel to waystones markers using the atlas map, even when stood near a sign.

After destroying a sign, waypoint or waystone, the marker stays on the atlas map.

**Comment by Rikshy** [comment]
fixed fast travel in a4f2eba 
labels not being removed is an issue with the main mod. I opened a ticket: https://github.com/AntiqueAtlasTeam/AntiqueAtlas/issues/262
