### ISSUE TITLE
Have the extra info follow the overlay.

### ISSUE THREAD

**Issue by crazyirishwrencher** [Rikshy/AntiqueAtlasExtras#3]
![2018-09-28_12 51 31](https://user-images.githubusercontent.com/34118405/46222076-442bf700-c31d-11e8-9bea-9bf9e6c10635.png)

When aligning the antique atlas overlay somewhere besides the default the extra info stays in place.

**Comment by Rikshy** [comment]
oh damn, i complete forgot to check then when i implemented text scaling - it was there, it just broke. 
I will release a new version soon :)

thanks for your report!
