### ISSUE TITLE
Feature suggestion: Add a config option for the minimap to always show

### ISSUE THREAD

**Issue by GreatestFool** [Rikshy/AntiqueAtlasExtras#6]
A config option for the minimap to always be shown would be great, such as showing the minimap of the first atlas it detects.

**Comment by Rikshy** [comment]
This would be a feature for the original mod i guess, i might make a PR for this tho

**Comment by Rikshy** [comment]
btw, there is an option for that in AntiqueAtlas but it only searches the Hotbar. Did you consider using this?
