### ISSUE TITLE
fast travel is currently broken

### ISSUE THREAD

**Issue by GeminiMarshdevil** [Rikshy/AntiqueAtlasExtras#7]
fast travel with signposts and waystones or any combination of those in the modpack, is currently not working.

**Comment by Rikshy** [comment]
Which modpack?

**Comment by GeminiMarshdevil** [comment]
my own modpack,  and it doesnt work even when its just signposts/atlas+extras in the game
modlist:
https://pastebin.com/rhK7xTqP
the modpack will be out sometime soon:tm: as Aion Revolutions on twitch/curse

**Comment by Studly234** [comment]
I think this mod just needs an update. Reverting to the previous version of the antique atlas mod (v 4.5.1) allows teleportation to work for me.

**Comment by Rikshy** [comment]
fixed in a4f2eba
keep in mind dependancy for signpost mod changed to version 1.08
