### ISSUE TITLE
Waystone labels remains after breaking waystone

### ISSUE THREAD

**Issue by JWTHDYTWA** [Rikshy/AntiqueAtlasExtras#8]
Atlas labels generated by waystones remains when waystone the label belong to is being broken.

**Comment by Rikshy** [comment]
Waystones from the Waystone mod or the Signpost mod?

**Comment by JWTHDYTWA** [comment]
Both of them.

**Comment by Rikshy** [comment]
This is wierd, I just tested it in my dev environment and it works :S

**Comment by Rikshy** [comment]
which version of Waystones and Signpost mod are you using?

**Comment by JWTHDYTWA** [comment]
Atlas Extras: 1.6
Waystones: 4.0.67
Signpost: 1.08.2

**Comment by Rikshy** [comment]
Are you on a server or sp?

**Comment by JWTHDYTWA** [comment]
Singleplayer. But on modpack

**Comment by Rikshy** [comment]
Issue with the main mod: https://github.com/AntiqueAtlasTeam/AntiqueAtlas/issues/262

**Comment by Rikshy** [comment]
Duplicate of #11
