### ISSUE TITLE
Russian localization

### ISSUE THREAD

**Issue by Shellyoung** [Rikshy/AntiqueAtlasExtras#9]
Forgive me Father for i have sinned and didn't find where to put my suggestion.

https://pastebin.com/5qsfhfit
or this one
https://www.mediafire.com/file/pzi27bu4t4c7rbc/ru_RU.lang/file

I maked sure that name of a waystone is the same as in Waystones mod russian localization

**Comment by Rikshy** [comment]
Thanks for the help :)
